### ISSUE TITLE
Question about input image

### ISSUE THREAD

**Issue by gravivector** [iro-cp/FCRN-DepthPrediction#14]
Hello,

What kind of image can be used as test image ? Trying to use your code and latest release of Tensorflow. As result I have got the errors:

Loading the model
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3.2\helpers\pydev\pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3.2\helpers\pydev\pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/code/py/ddpwfcrn/predict.py", line 71, in <module>
    main('C:/code/py/ddpwfcrn/NYU_ResNet-UpProj.npy', 'C:/code/py/ddpwfcrn/img/test.png')
  File "C:/code/py/ddpwfcrn/predict.py", line 66, in main
    pred = predict(model_path, image_paths)
  File "C:/code/py/ddpwfcrn/predict.py", line 47, in predict
    pred = sess.run(net.get_output(), feed_dict={input_node: img})
  File "C:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 767, in run
    run_metadata_ptr)
  File "C:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 944, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 228, 304, 4) for Tensor 'Placeholder:0', which has shape '(?, 228, 304, 3)'

**Comment by iro-cp** [comment]
Hello, 
The input is a RGB image of height 228 and width 304 (although other sizes could also be possible,  by changing the placeholder). Somehow your input seems to have four channels instead of three, which could be the reason for this error. I hope this helps :)

**Comment by rainy1798** [comment]
Hello，
I have a problem，I don't know how to use your methods to train。
Can you give me the original training code of matconvnet? I want to know more details about your experiment。So if you are willing，Please share your training source code of matconnet give me。thanks

**Comment by Lvhhhh** [comment]
i try many test pictures. they seem all have 4 channels? how to get 3 channels-pictures?
